export const Themes = [
  'light',
  // "dark",
  'cupcake',
  'bumblebee',
  // "retro",
  'valentine',
  // "halloween",
  // "garden",
  // "forest",
  // "aqua",
  // "luxury",
  'dracula',
  'lemonade',
  'night',
  'coffee',
  // "winter",
  // "sunset",
]

export const themeBackgrounds: any = {
  light: '/images/bg-light.jpg',
  // dark: "/images/bg-dark.jpeg",
  cupcake: '/images/bg-cupcake.jpg',
  bumblebee: '/images/bg-bumblebee.jpg',
  // retro: "/images/bg-retro.jpg",
  valentine: '/images/bg-valentine.jpg',
  // halloween: "/images/bg-halloween.jpg",
  // garden: "/images/bg-garden.jpg",
  // forest: "/images/bg-forest.jpg",
  // aqua: "/images/bg-aqua.jpg",
  // luxury: "/images/bg-luxury.jpg",
  dracula: '/images/bg-dracula.jpg',
  lemonade: '/images/bg-lemonade.jpg',
  night: '/images/bg-night.jpg',
  coffee: '/images/bg-coffee.jpg',
  // winter: "/images/bg-winter.jpg",
  // sunset: "/images/bg-sunset.jpg",
}

export const themeChats: any = {
  light: '/images/bg-light.jpg',
  cupcake: '/images/cupcake.png',
  bumblebee: '/images/bg-bumblebee.jpg',
  valentine: '/images/valentine.png',
  dracula: '/images/dracula.png',
  lemonade: '/images/lemonade.png',
  night: '/images/night.png',
  coffee: '/images/bg-coffee.jpg',
}
